name = "rdebrid-worker"
main = "functions/api/[[route]].ts"
compatibility_date = "2024-01-01"
account_id = "0a15c5f9d39350baa992ff9f48efc1c8"

[site]
bucket = "build/client"

# All secrets are set via wrangler secret put command:
# wrangler secret put USERNAME
# wrangler secret put PASSWORD  
# wrangler secret put DEBRID_TOKEN